AWSTemplateFormatVersion: '2010-09-09'
Description: AcmeLabs SpeakEasy Audio Processing

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - beta
      - prod
    Description: Environment for deployment (beta or prod)

  LambdaCodeBucket:
    Type: String
    Default: acmelabs-lambdas
    Description: The S3 bucket where Lambda function code is stored

  AudioBucketName:
    Type: String
    Default: acmelabs-speakeasy
    Description: The name of the audio S3 bucket (e.g., acmelabs-speakeasy-${Environment})

  UploadTriggerFunctionName:
    Type: String
    Default: acmelabs-speakeasy-upload
    Description: The name of the Upload Trigger Lambda function

  TranscribeFunctionName:
    Type: String
    Default: acmelabs-speakeasy-transcribe
    Description: The name of the Transcribe Lambda function

  TranslateFunctionName:
    Type: String
    Default: acmelabs-speakeasy-translate
    Description: The name of the Translate Lambda function

  SynthesizeFunctionName:
    Type: String
    Default: acmelabs-speakeasy-synthesize
    Description: The name of the Synthesize Lambda function

  UploadTriggerFunctionS3Key:
    Type: String
    Default: speakeasy/upload_trigger.zip
    Description: The prefix for the Upload Trigger Lambda function code files in the S3 bucket

  TranscribeFunctionS3Key:
    Type: String
    Default: speakeasy/transcribe.zip
    Description: The prefix for the Lambda function code files in the S3 bucket

  TranslateFunctionS3Key:
    Type: String
    Default: speakeasy/translate.zip
    Description: The prefix for the Lambda function code files in the S3 bucket

  SynthesizeFunctionS3Key:
    Type: String
    Default: speakeasy/synthesize.zip
    Description: The prefix for the Lambda function code files in the S3 bucket

  AudioProcessingStateMachineName:
    Type: String
    Default: acmelabs-speakeasy-audio-processing-state-machine
    Description: The name of the Audio Processing Step Functions state machine

  StepFunctionsRoleName:
    Type: String
    Default: acmelabs-speakeasy-step-functions-role
    Description: The name of the Step Functions IAM role

  LambdaExecutionRoleName:
    Type: String
    Default: acmelabs-speakeasy-lambda-execution-role
    Description: The name of the Lambda Execution IAM role

  TranscribeHandler:
    Type: String
    Default: transcribe.lambda_handler
    Description: The handler for the Transcribe Lambda function

  TranslateHandler:
    Type: String
    Default: translate.lambda_handler
    Description: The handler for the Translate Lambda function

  SynthesizeHandler:
    Type: String
    Default: synthesize.lambda_handler
    Description: The handler for the Synthesize Lambda function

Resources:
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AudioBucketName}-${Environment}"
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldOutputs
            Status: Enabled
            ExpirationInDays: 30
      Tags:
        - Key: Name
          Value: acmelabs-speakeasy-bucket

  UploadTriggerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${UploadTriggerFunctionName}-${Environment}"
      Handler: upload_trigger.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref UploadTriggerFunctionS3Key
      Runtime: python3.13
      Environment:
        STATE_MACHINE_ARN: !GetAtt AudioProcessingStateMachine.Arn
      Tags:
        - Key: Name
          Value: !Sub "${UploadTriggerFunctionName}-${Environment}"

  TranscribeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${TranscribeFunctionName}-${Environment}"
      Handler: !Ref TranscribeHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref TranscribeFunctionS3Key
      Runtime: python3.13
      Environment:
        Variables:
          S3_BUCKET: !Sub ${AudioBucketName}-${Environment}
      Tags:
        - Key: Name
          Value: !Sub "${TranscribeFunctionName}-${Environment}"

  TranslateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${TranslateFunctionName}-${Environment}"
      Handler: !Ref TranslateHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref TranslateFunctionS3Key
      Runtime: python3.13
      Environment:
        Variables:
          S3_BUCKET: !Sub ${AudioBucketName}-${Environment}
          TARGET_LANGUAGE: 'es'
      Tags:
        - Key: Name
          Value: !Sub "${TranslateFunctionName}-${Environment}"

  SynthesizeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${SynthesizeFunctionName}-${Environment}"
      Handler: !Ref SynthesizeHandler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref SynthesizeFunctionS3Key
      Runtime: python3.13
      Environment:
        Variables:
          S3_BUCKET: !Sub ${AudioBucketName}-${Environment}
      Tags:
        - Key: Name
          Value: !Sub "${SynthesizeFunctionName}-${Environment}"

  AudioProcessingStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      Definition:
        Comment: "Audio Processing State Machine"
        StartAt: "TranscribeAudio"
        States:
          TranscribeAudio:
            Type: Task
            Resource: !Sub "${TranscribeFunction.Arn}"
            Next: "TranslateText"
          TranslateText:
            Type: Task
            Resource: !Sub "${TranslateFunction.Arn}"
            Next: "SynthesizeSpeech"
          SynthesizeSpeech:
            Type: Task
            Resource: !Sub "${SynthesizeFunction.Arn}"
            End: true
      RoleArn: !GetAtt StepFunctionsRole.Arn
      StateMachineName: !Sub "${AudioProcessingStateMachineName}-${Environment}"
      Tags:
        - Key: Name
          Value: !Sub "${AudioProcessingStateMachineName}-${Environment}"
      #LoggingConfiguration:
      #  Level: ALL
      #  Destinations:
      #    - CloudWatchLogsLogGroup:
      #        LogGroupArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/vendedlogs/states/${AudioProcessingStateMachineName}-${Environment}/*"

  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${StepFunctionsRoleName}-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !GetAtt TranscribeFunction.Arn
                  - !GetAtt TranslateFunction.Arn
                  - !GetAtt SynthesizeFunction.Arn
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/vendedlogs/states/${AudioProcessingStateMachineName}-${Environment}/*'
      Tags:
        - Key: Name
          Value: !Sub "${StepFunctionsRoleName}-${Environment}"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaExecutionRoleName}-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AudioProcessingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - translate:TranslateText
                  - polly:SynthesizeSpeech
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:s3:::${AudioBucket}/audio_inputs/*'
                  - !Sub 'arn:aws:s3:::${AudioBucket}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${UploadTriggerFunctionName}-${Environment}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${TranscribeFunctionName}-${Environment}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${TranslateFunctionName}-${Environment}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SynthesizeFunctionName}-${Environment}'
        - PolicyName: TranscribeExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                Resource:
                  - !Sub '*'
      Tags:
        - Key: Name
          Value: !Sub "${LambdaExecutionRoleName}-${Environment}"

  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UploadTriggerFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${AudioBucket}'

Outputs:
  AudioBucketName:
    Value: !Ref AudioBucket
    Description: Name of the audio S3 bucket

  TranscribeFunctionArn:
    Value: !GetAtt TranscribeFunction.Arn
    Description: ARN of the Transcribe Lambda function

  TranslateFunctionArn:
    Value: !GetAtt TranslateFunction.Arn
    Description: ARN of the Translate Lambda function

  SynthesizeFunctionArn:
    Value: !GetAtt SynthesizeFunction.Arn
    Description: ARN of the Synthesize Lambda function

  StateMachineArn:
    Value: !GetAtt AudioProcessingStateMachine.Arn
    Description: ARN of the audio processing Step Functions state machine

  StepFunctionsRoleArn:
    Value: !GetAtt StepFunctionsRole.Arn
    Description: ARN of the Step Functions role

  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Description: ARN of the Lambda execution role

  LambdaCodeBucketName:
    Value: !Ref LambdaCodeBucket
    Description: Name of the S3 bucket where Lambda function code is stored
