name: Destroy Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to destroy: beta or prod.'
        required: true
        type: choice
        options:
          - beta
          - prod

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delete CloudFormation Stack
        run: |
          # Construct the prefix based on the selected environment
          PREFIX="AcmeLabsSpeakEasy-${{ github.event.inputs.environment }}"
          
          # Find the stack name that starts with the known prefix
          STACK_NAME=$(aws cloudformation list-stacks --query "StackSummaries[?starts_with(StackName, '$PREFIX')].StackName" --output text)

          # Check if a stack was found and delete it
          if [ -n "$STACK_NAME" ]; then
            echo "Deleting stack: $STACK_NAME"
            aws cloudformation delete-stack --stack-name "$STACK_NAME"
            echo "Stack $STACK_NAME is being deleted."
          else
            echo "No stack found with the prefix $PREFIX. Skipping deletion."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
