name: Destroy Resources

on:
  workflow_dispatch:  # Enable manual trigger
    inputs:
      environment:
        description: 'Select environment to destroy: beta or prod.'
        required: true
        type: choice
        options:
          - beta
          - prod

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CloudFormation stack exists
        id: check_stack
        run: |
          # Construct the stack name based on the selected environment
          STACK_NAME="AcmeLabsSpeakEasy-${{ github.event.inputs.environment }}"
          echo "STACK_NAME=$STACK_NAME" >> $GITHUB_ENV  # Export STACK_NAME as an environment variable
          
          # Check if the stack exists
          if aws cloudformation describe-stacks --stack-name "$STACK_NAME" 2>/dev/null; then
            echo "Stack $STACK_NAME exists. Proceeding to deletion."
            echo "DEPLOY_STACK=true" >> $GITHUB_ENV
          else
            echo "Stack $STACK_NAME does not exist. Skipping deletion."
            echo "Exiting the workflow."
            exit 1  # Exit with an error code
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Delete CloudFormation stack
        if: env.DEPLOY_STACK == 'true'
        run: |
          # Use the constructed stack name to delete the stack
          STACK_NAME="AcmeLabsSpeakEasy-${{ github.event.inputs.environment }}"
          aws cloudformation delete-stack --stack-name "$STACK_NAME"
          echo "Stack $STACK_NAME is being deleted."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
